language: c
compiler: 
  - gcc
before_install:
  - sudo apt-get install libsdl1.2-dev libsdl-gfx1.2-dev check
install:
  - mkdir build/ 
  - cd build/
  - cmake ..
  - make
script:
  - cd build/
  - make test
